In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pycaret as py

In [2]:
data = pd.read_csv("insurance.csv")
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
from pycaret.regression import*
s =setup(data,target='charges',train_size=0.8,session_id=123,normalize=True,
         normalize_method='minmax')

In [4]:
compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

GradientBoostingRegressor(random_state=123)

In [5]:
#Creation du meilleur modele
best = create_model("gbr")

In [ ]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [7]:
new_data = data.copy()
new_data.drop('charges',axis=1,inplace=True)
new_data.head()

   age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

In [8]:
predictions = predict_model(best,data=new_data)
predictions.head()

   age     sex        bmi  children smoker     region  prediction_label
0   19  female  27.900000         0    yes  southwest      18272.749301
1   18    male  33.770000         1     no  southeast       3682.733492
2   28    male  33.000000         3     no  southeast       6757.164012
3   33    male  22.705000         0     no  northwest      11189.187113
4   32    male  28.879999         0     no  northwest       3847.149404

In [9]:
#Optimisation
tuned_best = tune_model(best)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [10]:
#Optimisation controlee
xgb_grid = {"max_depth":[None,2,4,6,8,10,12],"max_features":[50,100,150,200,250]}
#Tune model
tuned_xgb = tune_model(best,custom_grid=xgb_grid,optimize='MSE')

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [11]:
#Optimisation avec OPTUNA
tuned_best_opt = tune_model(best,search_library='optuna')

In [16]:
#Comparaison des modeles suivant un critere
best_mae_models = compare_models(sort='MAE',n_select=3)
best_mae_models

[GradientBoostingRegressor(random_state=123),
 <catboost.core.CatBoostRegressor at 0x1c4ee0599d0>,
 ExtraTreesRegressor(n_jobs=-1, random_state=123)]